### ISSUE TITLE
Should sybil nodes forward query messages?

### ISSUE THREAD

**Issue by andreazampieri** [geektoni/whanau-sybil-proof-DHT#10]
I think that sybil nodes should just make the query fail, simulating a 'missing_key' error in the query.
As written in the paper (end of paragraph 5.1)

> Then, honest nodes might have to send many useless query messages to Sybil nodes before eventually querying an honest node

To implement this we should  tweak the function `randomWalk()` in order to stop the walk when a sybil node is encountered. Right now, sybil nodes just don't reply if they are asked for the value, but I think is a behaviour too gentle and not realistic

**Comment by geektoni** [comment]
Are they not doing it now? I mean, I thought we implemented that Sybil
nodes returns null when they are queried for a given key.

**Comment by geektoni** [comment]
Since we are assuming that there is a sparse cut between an honest and a Sybil region of the graph, there is still the possibility for a node to escape the Sybil region by doing its `randomWalk()`, therefore it may be not completely accurate to "cut off" a walk when we encounter a sybil node. 

Moreover, since we are clustering the sybil nodes, an honest node **will** waste many queries messages in order to find a key, because it will mainly find sybil nodes around the target key.

**Comment by geektoni** [comment]
Fixed here 2b5130f9f06f4462ad5b39efdfff6a3923e8ac52.
